#!/usr/bin/env node

// build and deploy site

const shell = require('shelljs')

const cmd = `
npm run --silent --prefix packages/neomem-domain-site build > site/public/index.html
`
shell.exec(cmd)

// const composefile = `setups/compose.yaml`
// let args = `--file ${composefile}`

// const composefile2 = `setups/${setup}/compose-${setup}.yaml`
// if (fs.existsSync(composefile2)) {
//   args += ` --file ${composefile2}`
// }

// const envfile = `setups/.env`
// if (fs.existsSync(envfile)) {
//   args += ` --env-file ${envfile}`
// }

// let flags = ''
// if (cmd == 'startd') {
//   flags = '--detach'
// }

// if (cmd === 'start' || cmd === 'startd') {
//   // pull any required images in the docker-compose files and start services.
//   const cmd = `SETUP=${setup} docker-compose ${args} pull ${services} && SETUP=${setup} docker-compose ${args} up --build ${flags} ${services}`
//   console.log(cmd)
//   shell.exec(cmd)
// } else if (cmd === 'stop') {
//   const cmd = `SETUP=${setup} docker-compose ${args} down ${services}`
//   console.log(cmd)
//   shell.exec(cmd)
// }
