# docker-compose file

version: '3.8'

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:2.3.0-pg13
    # image: timescale/timescaledb:2.3.0-pg11 # pg11 so can use AGE graphs
    ports:
      - $PGPORT:5432/tcp
    environment:
      POSTGRES_DB: $PGDATABASE
      POSTGRES_USERNAME: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
    volumes:
      - ./$SETUP/volumes/timescaledb/data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - ladder99
    logging:
      options:
        max-size: '1m'

  # gateway:
  #   container_name: gateway
  #   build:
  #     context: ./packages/neomem-gateway
  #   ports:
  #     - '4000:4000'
  #   # environment:
  #   #   - HOST=neomem
  #   # volumes:
  #   #   - ../volumes/neomem/config:/etc/neomem
  #   networks:
  #     - neomem

networks:
  ladder99:
    name: ladder99
