version: '3.7'

services:
  gateway:
    container_name: gateway
    build:
      context: ./packages/neomem-gateway
    # ports:
    #   - '8080:8080'
    environment:
      - DB_DB=neomem
      - DB_USER=neomem
      - DB_PASSWORD=neomem
    # volumes:
    #   - ../volumes/neomem/config:/etc/neomem
    networks:
      - neomem

networks:
  neomem:
    name: ladder99
