# apache metamodel-membrane experiments.
# use with https://github.com/Huachao/vscode-restclient


GET http://localhost:8080

###

PUT http://localhost:8080/neomem
Content-Type: application/json

{}

###

GET http://localhost:8080/neomem

###

PUT http://localhost:8080/neomem/postgres
Content-Type: application/json

{
  "type": "jdbc",
  "url": "jdbc:postgresql://example-postgres/membrane",
  "username": "membrane",
  "password": "secret"
}

###

PUT http://localhost:8080/neomem/couchdb
Content-Type: application/json

{
  "type": "couchdb",
  "hostname": "example-couchdb",
  "username": "membrane",
  "password": "secret"
}

###

PUT http://localhost:8080/neomem/pojo
Content-Type: application/json

{
  "type": "pojo",
  "table-defs": "hello_world (greeting VARCHAR, who VARCHAR); foo (bar INTEGER, baz DATE);"
}

###

GET http://localhost:8080/neomem/pojo

###

GET http://localhost:8080/neomem/pojo/s/information_schema

# {
#   "type": "schema",
#   "name": "information_schema",
#   "datasource": "pojo",
#   "tenant": "neomem",
#   "tables": [
#     {
#       "name": "tables",
#       "uri": "/neomem/pojo/s/information_schema/t/tables"
#     },
#     {
#       "name": "columns",
#       "uri": "/neomem/pojo/s/information_schema/t/columns"
#     },
#     {
#       "name": "relationships",
#       "uri": "/neomem/pojo/s/information_schema/t/relationships"
#     }
#   ]
# }


###

GET http://localhost:8080/neomem/pojo/s/Schema

# {
#   "type": "schema",
#   "name": "Schema",
#   "datasource": "pojo",
#   "tenant": "neomem",
#   "tables": [
#     {
#       "name": "foo",
#       "uri": "/neomem/pojo/s/Schema/t/foo"
#     },
#     {
#       "name": "hello_world",
#       "uri": "/neomem/pojo/s/Schema/t/hello_world"
#     }
#   ]
# }

###

GET http://localhost:8080/neomem/pojo/s/Schema/t/foo

# {
#   "type": "table",
#   "name": "foo",
#   "schema": "Schema",
#   "datasource": "pojo",
#   "tenant": "neomem",
#   "columns": [
#     {
#       "name": "bar",
#       "uri": "/neomem/pojo/s/Schema/t/foo/c/bar"
#     },
#     {
#       "name": "baz",
#       "uri": "/neomem/pojo/s/Schema/t/foo/c/baz"
#     }
#   ]
# }

###

POST http://localhost:8080/neomem/pojo/s/Schema/t/foo/d
Content-Type: application/json

{
  "insert": [
    {"bar": 42, "baz": null}
  ]
}

# {
#   "status": "ok",
#   "updated-rows": null,
#   "deleted-rows": null,
#   "inserted-rows": null,
#   "generated-keys": null
# }

###

GET http://localhost:8080/neomem/pojo/s/Schema/t/foo/d

# {
#   "type": "dataset",
#   "headers": [
#     "foo.bar",
#     "foo.baz"
#   ],
#   "data": []
# }

###

GET http://localhost:8080/neomem/datasources

# {
#   "type":"datasource",
#   "name":"datasources",
#   "tenant":"neomem",
#   "updateable":null,
#   "query_uri":"/neomem/datasources/query",
#   "schemas":null
# }
