sources:
  - name: neo4j
    handler:
      graphql:
        endpoint: http://localhost:4101/graphql
    # transforms:
    #   - prefix:
    #       value: neo4j
  - name: bookmarks
    handler:
      graphql:
        endpoint: http://localhost:4103/graphql
    # transforms:
    #   - prefix:
    #       value: chrome
