sources:
  - name: neo4j
    handler:
      graphql:
        endpoint: http://localhost:4101/graphql
    transforms:
      - encapsulate:
          applyTo:
            query: true
            mutation: true
            subscription: false
  - name: bookmarks
    handler:
      graphql:
        endpoint: http://localhost:4103/graphql
    transforms:
      - encapsulate:
          applyTo:
            query: true
            mutation: false
            subscription: false
