data:
  - path: neo4j
    driver: neo4j
    start: home

  - path: desktop
    driver: filesys
    start: /Users/bburns/Desktop

  - path: dropbox
    driver: filesys
    start: /Users/bburns/Dropbox

  - path: chrome
    driver: bookmarks
    start: /
