data:
  - path: neo4j
    driver: neo4j
    source: home

  - path: desktop
    driver: filesys
    source: /Users/bburns/Desktop

  - path: dropbox
    driver: filesys
    source: /Users/bburns/Dropbox

  - path: chrome
    driver: bookmarks
    source: /
