baseURL = "https://neomem.io"
languageCode = "en-us"
title = "Neomem.io"

theme = "ananke"
themesDir = "./themes"
resourceDir = "./resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Neomem.io"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/neomem.ico"
  # site_logo = "images/neomem.png"
  description = "An open-source information manager"
  facebook = ""
  twitter = "https://twitter.com/neomem_io"
  instagram = ""
  youtube = ""
  github = "https://github.com/bburns/neomem"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/landscape.jpg"
  recent_posts_number = 2
