// mtconnect application
// capture agent data and write to database

import pg from 'pg' // postgres driver - import { Client } from 'pg' gives error
const { Client } = pg

;(async function () {
  const client = new Client()
  await client.connect() // uses envars PGHOST, PGPORT, etc
  await setupTables(client)
})()

async function setupTables(client) {
  const sql = `
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

-- for experimenting
DROP TABLE IF EXISTS nodes;
DROP TABLE IF EXISTS edges;
DROP TABLE IF EXISTS history;

CREATE TABLE IF NOT EXISTS nodes (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  props jsonb
);

CREATE TABLE IF NOT EXISTS edges (
  from int NOT NULL,
  to int NOT NULL,
  props jsonb,
  CONSTRAINT fk_from FOREIGN KEY(from) REFERENCES nodes(id),
  CONSTRAINT fk_to FOREIGN KEY(to) REFERENCES nodes(id)
);

CREATE TABLE IF NOT EXISTS history (
  id int NOT NULL,
  time timestamptz NOT NULL,
  props jsonb,
  CONSTRAINT fk_node FOREIGN KEY(id) REFERENCES nodes(id)
);

SELECT create_hypertable('history', 'time', if_not_exists => TRUE);

`
  console.log(`Creating db structures if not there...`)
  await client.query(sql)
}
