// use this to experiment with datamodel - use for testing also.
// store nodes and edges.

// _id, _from, _to are from arangodb

//. call these items and relations, as the ui will use?

// consider this the serialized form - the db would read them
// and instantiate the indexes, or store those separately

export const data = {
  nodes: [
    {
      id: 1,
      name: 'plecy',
      alias: 'plecostomus',
      notes: 'a catfish',
      type: 'fish',
      public: true,
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 2,
      name: 'fish',
      type: 'folder',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 3,
      name: 'zoey',
      type: 'cat',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 4,
      name: 'default view',
      type: 'view',
      columns: [5],
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 5,
      type: 'column',
      note: 'name',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 6,
      type: 'column',
      note: 'type',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 7,
      type: 'column',
      note: 'description',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 8,
      type: 'field',
      name: 'name',
      display: 'Name',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 9,
      type: 'field',
      name: 'type',
      display: 'Type',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 10,
      type: 'field',
      name: 'description',
      display: 'Description',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    {
      id: 11,
      type: 'blog',
      name: 'neoblog',
      notes: `This is my blog.`,
      public: true,
      created: '2021-04-25T10:25:00',
      modified: null,
    },
    {
      id: 13,
      type: 'column',
      notes: 'notes',
      created: '2021-04-25T14:25:00',
      modified: null,
    },
    {
      id: 14,
      type: 'place',
      name: 'forest',
      notes: 'a dreary forest with faint light filtering from above',
      created: '2021-05-08T14:25:00',
      modified: null,
    },
    {
      id: 15,
      type: 'place',
      name: 'field',
      notes: 'a grassy field stretches out, covered in wildflowers',
      created: '2021-05-08T14:25:00',
      modified: null,
    },
    {
      id: 16,
      name: 'trees',
      created: '2021-05-08T14:25:00',
      modified: null,
    },
    {
      id: 17,
      name: 'leaves',
      created: '2021-05-08T14:25:00',
      modified: null,
    },
    {
      id: 18,
      name: 'A new blog, using GitHub Pages / Jekyll',
      created: '2021-05-15T14:25:00',
      modified: null,
      type: 'post',
      public: true,
      notes: `Here is my new blog, stored in / generated by Neomem. I'll try to make it look nicer later.

I'm hoping that writing a blog in Neomem will get me to make it functional faster. 

I've been spending weekends lately working on it, but every time I come back to it I think - this is too complex - and try again. Maybe eventually it'll settle on a good architecture. 

Last week I found ArangoDB, which is faster and uses less memory than Neo4j, and I like the query language a bit better. So I'm going to try that for the main storage.

But for now, this is stored in a json file along with other test data. Keeping it as simple as possible for now.`,
    },
    {
      id: 19,
      name: `ArangoDB`,
      created: '2021-05-16T23:14:00',
      modified: null,
      type: 'post',
      public: true,
      notes: `I'm trying out ArangoDB in another project - it took a while to figure out how to initialize the database. But both of these projects will help with the design of the other.`,
    },
    {
      id: 20,
      name: `PostgreSQL and A Graph Extension (AGE)`,
      created: '2021-05-22T06:18:53',
      modified: null,
      type: 'post',
      public: true,
      notes: `I think I'll try PostgreSQL for the main backend - there is a graph extension for it, a time-series extension, a GIS extension, and you can store JSON/JSONB data in fields. So it seems to have the best of everything.`,
    },
    {
      id: 21,
      name: `A new blog, using Hugo`,
      created: '2021-02-07',
      type: 'post',
      public: true,
      notes: `Needing a new site, and wanting to have a blog on it, I looked at a few static site generators -

- Eleventy (11ty) - JavaScript
- Gatsby - React/JavaScript/GraphQL
- Hugo - Go

Eleventy didn't seem to have a good architecture, and the documentation wasn't very encouraging. Gatsby seemed interesting and well-designed, but was terribly slow. Hugo is _fast_, and seems well planned out and organized.

<!-- compare github stars, codebase size -->      
`,
    },
    {
      id: 22,
      name: `Types`,
      created: '2021-02-08',
      type: 'post',
      public: true,
      notes: `I'm trying to figure out how to handle types - Neomem needs to understand a set of basic types, and to translate between those and each datasource's types.

e.g. Chrome Bookmarks have a 'date_added' field, which is based on the year 1601. We'll need to translate that to the 'created' field, which is an ISO datestring like '2021-02-08', and vice-versa.

We could store a library of these datatypes, usable by different datasources. e.g. 'date1601', in case some other datasource needed it also.

Put this in neomem-util? neomem-types? neomem-data?

Types need to be dynamic, as with neo4j - user will be able to define new types/labels as needed, and they can contain fields, or relations with other nodes.

Should we start developing the neo4j datasource to exercise all this stuff? Should at least sketch out what it needs.
`,
    },
    {
      id: 23,
      name: `Stardog Knowledge Graph`,
      created: '2021-05-23T19:21:53',
      modified: null,
      type: 'post',
      public: true,
      notes: `Getting back to the Gateway, which needs to consolidate different datasources. I Googled around and wound up at Stardog Knowledge Graph - it's a free platform for building knowledge graphs on different datasources, which is just what we need!`,
    },
  ],

  edges: [
    {
      from: 1,
      to: 2,
      type: 'contains',
      created: '2021-04-25T04:25:00',
      modified: null,
    },
    { from: 5, to: 8, type: 'shows' },
    { from: 6, to: 9, type: 'shows' },
    { from: 7, to: 10, type: 'shows' },
    { from: 14, to: 16, type: 'contains' },
    { from: 14, to: 17, type: 'contains' },
  ],
}
