# baseURL = "https://neomem.io"
baseURL = "https://neomem.web.app"
languageCode = "en-us"
title = "Neomem.io"
themesDir = "./themes"
resourceDir = "./resources"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/neomem.ico"
  # site_logo = "images/neomem.png"
  description = "An open-source information manager"
  twitter = "https://twitter.com/bburnskm"
  github = "https://github.com/bburns/Neomem"
  instagram = ""
  youtube = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  facebook = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "images/landscape.jpg"
  recent_posts_number = 10 # on front page
  cover_dimming_class = "bg-black-20"
  custom_css = ["css/styles.css"]
  disable_share = true
  omit_header_text = true